title:             "Italia Design Jekyll Theme - by G.Gentili 2018"
description:       "A theme for Jekyll or GitHub Pages derived from Clean Blog by Start Bootstrap"
baseurl:           "/"
url:               "https://ggentili.github.io/Italia-Design-Jekyll-Theme/"

# Colors and styles
personalizza_css: false

# Header data
header_parent_title: Nome ente sovraordinato
header_parent_url: "http://entepubblico-sovraordinato.it"
header_language_selector: false
header_logo: https://placehold.it/75x80?text=header_logo
header_title: Nome ente o titolo del sito
header_subtitle: sottotitolo
search: true
search_full_content: false
mega_menu: true    # if true, require _data/menu.yml
mega_menu_accedi: false

# Social profiles
social_block: true
social_username: "&commat;Account"    # short
medium_username: abcuser
facebook_username: abcuser
twitter_username:  abcuser
youtube_username: abcuser
linkedin_username:
github_username: abcuser

# Footer data
footer_logo: https://placehold.it/75x80?text=footer_logo
footer_title: Nome ente
footer_subtitle: sottotitolo
recapiti1: Recapiti
recapiti2: Via autem reiciendis maiores
recapiti3: autem reiciendis maiores
recapiti4: Tel. (+00) 00.0000.0000
email: your-email@example.it
pec: your-pec@example.it
privacy_url: "privacy"
note_legali_url: "note_legali"
contatti_url: "contatti"

# Home sections
links_buttons: true
links_buttons_title:
posts_list: true
posts_list_title: Autem reiciendis post
section_lists: true
section_lists_title: Dignissimos recusandae landing
twitter_list: true
twitter_list_title: Twitter@amministrazione
links_leads: true
links_leads_title: A est rerum leads

# Build settings
# permalink: /:categories/:title/
markdown:          kramdown
paginate:          5
paginate_path:     "/posts/page:num/"#
locale: "it-IT"
plugins:
  - jekyll-feed
  - jekyll-paginate

defaults:
# _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      toc: false
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: false
      read_time: false
      comments: false
      share: true
      related: false
  # _foo
  - scope:
      path: ""
      type: foo
    values:
      layout: single
